default:
    tags:
        - apap

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == 'main'

before_script:
  - docker info
  - javac -version

variables:
  IMAGE_OPENJDK_GRADLE: gradle:7.3.3-jdk17-alpine
  IMAGE_DOCKER_DIND: docker:20.10.16

stages:
  - build
  - build-image
  - publish-image
  - deploy

build:
  image: $IMAGE_OPENJDK_GRADLE
  stage: build
  script:
    - echo "Compiling the code..."
    - sh build-all.sh
  artifacts:
    paths:
      - RumahSehatAPI/build/libs/RumahSehatAPI-0.0.1-SNAPSHOT.jar
      - RumahSehatWeb/build/libs/RumahSehatWeb-0.0.1-SNAPSHOT.jar

build-image:
  stage: build-image
  script:
    - echo "Building Docker Image..."
    - docker build -t $REGISTRY_SERVER/faris.haidar/apap-090-web:$CI_COMMIT_SHORT_SHA RumahSehatWeb
    - docker build -t $REGISTRY_SERVER/faris.haidar/apap-090-web:latest RumahSehatWeb
    - docker build -t $REGISTRY_SERVER/faris.haidar/apap-090-api:$CI_COMMIT_SHORT_SHA RumahSehatAPI
    - docker build -t $REGISTRY_SERVER/faris.haidar/apap-090-api:latest RumahSehatAPI
    - docker build -t $REGISTRY_SERVER/faris.haidar/apap-090-nginx:$CI_COMMIT_SHORT_SHA nginx
    - docker build -t $REGISTRY_SERVER/faris.haidar/apap-090-nginx:latest nginx

publish-image:
  stage: publish-image
  script:
    - echo "Publishing Docker Image..."
    - echo $REGISTRY_SERVER
    - echo $REGISTRY_PASSWORD | docker login --username $REGISTRY_USERNAME --password-stdin $REGISTRY_SERVER
    - docker push $REGISTRY_SERVER/faris.haidar/apap-090-web:$CI_COMMIT_SHORT_SHA
    - docker push $REGISTRY_SERVER/faris.haidar/apap-090-web:latest
    - docker push $REGISTRY_SERVER/faris.haidar/apap-090-api:$CI_COMMIT_SHORT_SHA
    - docker push $REGISTRY_SERVER/faris.haidar/apap-090-api:latest
    - docker push $REGISTRY_SERVER/faris.haidar/apap-090-nginx:$CI_COMMIT_SHORT_SHA
    - docker push $REGISTRY_SERVER/faris.haidar/apap-090-nginx:latest

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

  script:
    - echo "Deploy to server..."
    - rsync -rah ./docker-compose.yml db.env "${DEPLOY_USERNAME}@${DEPLOY_SERVER}":"~/apap-090"
    - ssh "${DEPLOY_USERNAME}@${DEPLOY_SERVER}" "cd ~/apap-090/ && docker-compose down && docker-compose pull && docker-compose up --build -d"

