version: '2'
services:
  nginx:
    image: apap-registry.cs.ui.ac.id/faris.haidar/apap-090-nginx
    restart: always
    networks:
      - frontend-network
      - backend-network
    ports:
      - "10090:80"
    depends_on:
      - rumah-sehat-web
      - rumah-sehat-api
      
  rumah-sehat-web:
    image: apap-registry.cs.ui.ac.id/faris.haidar/apap-090-web
    restart: always
    volumes:
      - ./RumahSehatWeb/file-storage:/file-storage
      - ./RumahSehatWeb/log:/log
    env_file:
      - db.env
    depends_on:
      - db
    networks:
      - backend-network
      
  rumah-sehat-api:
    image: apap-registry.cs.ui.ac.id/faris.haidar/apap-090-api
    restart: always
    volumes:
      - ./RumahSehatAPI/file-storage:/file-storage
      - ./RumahSehatAPI/log:/log
    env_file:
      - db.env
    depends_on:
      - db
    networks:
      - backend-network
      
  db:
    image: mariadb:10.4.24
    restart: always
    env_file:
      - db.env
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
      - backend-network

networks:
  frontend-network:
  backend-network:
